version: "3.2"
services:

  # rs-sh1
  rs-sh1-01:
    image: mongo:4.4.2
    volumes:
      - rs-sh1-01:/data/db
    expose:
    - 27011
    ports:
      - 27011:27011
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27011", "--replSet", "rs-sh1", "--shardsvr" ]
  rs-sh1-02:
    image: mongo:4.4.2
    volumes:
      - rs-sh1-02:/data/db
    expose:
    - 27012
    ports:
    - 27012:27012
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27012", "--replSet", "rs-sh1", "--shardsvr" ]
  rs-sh1-03:
    image: mongo:4.4.2
    volumes:
      - rs-sh1-03:/data/db
    expose:
    - 27013
    ports:
    - 27013:27013
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27013", "--replSet", "rs-sh1", "--shardsvr" ]

  # rs-sh2
  rs-sh2-01:
    image: mongo:4.4.2
    volumes:
      - rs-sh2-01:/data/db
    expose:
    - 27014
    ports:
      - 27014:27014
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27014", "--replSet", "rs-sh2", "--shardsvr" ]
  rs-sh2-02:
    image: mongo:4.4.2
    volumes:
      - rs-sh2-02:/data/db
    expose:
    - 27015
    ports:
    - 27015:27015
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27015", "--replSet", "rs-sh2", "--shardsvr" ]
  rs-sh2-03:
    image: mongo:4.4.2
    volumes:
      - rs-sh2-03:/data/db
    expose:
    - 27016
    ports:
    - 27016:27016
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27016", "--replSet", "rs-sh2", "--shardsvr" ]

  # rs-config
  rs-config-01:
    image: mongo:4.4.2
    volumes:
      - rs-config-01:/data/configdb
    expose:
    - 27017
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27017", "--replSet", "rs-config", "--configsvr" ]
  rs-config-02:
    image: mongo:4.4.2
    volumes:
      - rs-config-02:/data/configdb
    expose:
    - 27018
    ports:
    - 27018:27018
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27018", "--replSet", "rs-config", "--configsvr" ]
  rs-config-03:
    image: mongo:4.4.2
    volumes:
      - rs-config-03:/data/configdb
    expose:
    - 27019
    ports:
    - 27019:27019
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27019", "--replSet", "rs-config", "--configsvr" ]

  # rs-mongos
  rs-mongos:
    image: mongo:4.4.2
    expose:
    - 27020
    ports:
      - 27020:27020
    entrypoint: [ "/usr/bin/mongos", "--bind_ip_all", "--port", "27020", "--configdb", "rs-config/rs-config-01:27017,rs-config-02:27018,rs-config-03:27019" ]
volumes:
  rs-sh1-01:
  rs-sh1-02:
  rs-sh1-03:
  rs-sh2-01:
  rs-sh2-02:
  rs-sh2-03:
  rs-config-01:
  rs-config-02:
  rs-config-03: