version: "3"
services:
  rs-sh2-01:
    image: mongo:4.4.2
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./rs-sh2-01:/data/db
    expose:
    - 27014
    ports:
      - 27014:27014
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27014", "--replSet", "rs-sh2", "--shardsvr" ]
  rs-sh2-02:
    image: mongo:4.4.2
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./rs-sh2-02:/data/db
    expose:
    - 27015
    ports:
    - 27015:27015
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27015", "--replSet", "rs-sh2", "--shardsvr" ]
  rs-sh2-03:
    image: mongo:4.4.2
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./rs-sh2-03:/data/db
    expose:
    - 27016
    ports:
    - 27016:27016
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "27016", "--replSet", "rs-sh2", "--shardsvr" ]